name: Build Executable

on:
  push:
    branches:
      - main  # Change this if your main branch is named differently

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment to create .exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile script.py  # Replace with your script name

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/script.exe  # Change if your exe name differs
